project_id = "qgzbrwljsuhtsudcfpyj"

[functions.pharma-chat]
verify_jwt = false

[functions.generate-analysis]
verify_jwt = false

[functions.medicine-detection]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false
